package view;

import controller.CreateUserController;
import controller.DeleteUserController;
import controller.TransactionalController;
import controller.UpdateUserController;
import controller.UsersController;
import controller.UsersListController;
import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import model.UserDAO;

/**
 *
 * @author migue
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private static CreateUserPanel createPanel;
    private static UsersListPanel listPanel;
    private static DeleteUserPanel deletePanel;
    private static EditUserPanel updatePanel;
    private static TransactionalPanel transactionalPanel;

    public MainJFrame() {
        System.out.println("Constructor Frame");
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/resources/icon.png")).getImage());
        setLogo();
        createPanel = new CreateUserPanel();
        listPanel = new UsersListPanel();
        deletePanel = new DeleteUserPanel();
        updatePanel = new EditUserPanel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelUsers = new javax.swing.JPanel();
        createUserBtn = new javax.swing.JButton();
        editUserBtn = new javax.swing.JButton();
        deleteUserBtn = new javax.swing.JButton();
        usersListBtn = new javax.swing.JButton();
        jPanelContainer = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        jPanelTransactions = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 255));
        setLocationByPlatform(true);
        setResizable(false);

        jPanelUsers.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuarios"));

        createUserBtn.setText("Crear Usuario");
        createUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserBtnActionPerformed(evt);
            }
        });

        editUserBtn.setText("Editar contraseña");
        editUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserBtnActionPerformed(evt);
            }
        });

        deleteUserBtn.setText("Eliminar Usuario");
        deleteUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserBtnActionPerformed(evt);
            }
        });

        usersListBtn.setText("Listar Usuarios");
        usersListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersListBtnActionPerformed(evt);
            }
        });

        jPanelContainer.setPreferredSize(new java.awt.Dimension(195, 140));

        logoLabel.setPreferredSize(new java.awt.Dimension(195, 140));
        jPanelContainer.add(logoLabel);

        javax.swing.GroupLayout jPanelUsersLayout = new javax.swing.GroupLayout(jPanelUsers);
        jPanelUsers.setLayout(jPanelUsersLayout);
        jPanelUsersLayout.setHorizontalGroup(
            jPanelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usersListBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
        );
        jPanelUsersLayout.setVerticalGroup(
            jPanelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsersLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(createUserBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editUserBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteUserBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usersListBtn)
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(jPanelUsersLayout.createSequentialGroup()
                .addComponent(jPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelTransactions.setBorder(javax.swing.BorderFactory.createTitledBorder("Transacciones"));

        javax.swing.GroupLayout jPanelTransactionsLayout = new javax.swing.GroupLayout(jPanelTransactions);
        jPanelTransactions.setLayout(jPanelTransactionsLayout);
        jPanelTransactionsLayout.setHorizontalGroup(
            jPanelTransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );
        jPanelTransactionsLayout.setVerticalGroup(
            jPanelTransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTransactions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTransactions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserBtnActionPerformed
        // TODO add your handling code here:
        setCustomContentPanel(createPanel);
    }//GEN-LAST:event_createUserBtnActionPerformed

    private void editUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserBtnActionPerformed
        // TODO add your handling code here:
        setCustomContentPanel(updatePanel);
    }//GEN-LAST:event_editUserBtnActionPerformed

    private void deleteUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserBtnActionPerformed
        // TODO add your handling code here:
        setCustomContentPanel(deletePanel);
    }//GEN-LAST:event_deleteUserBtnActionPerformed

    private void usersListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersListBtnActionPerformed
        // TODO add your handling code here:
        setCustomContentPanel(listPanel);
    }//GEN-LAST:event_usersListBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
            System.out.println(e.getMessage());
        }
        java.awt.EventQueue.invokeLater(() -> {
            MainJFrame mainFrame = new MainJFrame();
            UserDAO userDAO = new UserDAO(mainFrame);
            mainFrame.setTitle("Java Bank");
            mainFrame.setLocationRelativeTo(null);
            mainFrame.setVisible(true);
            CreateUserController createController = new CreateUserController(createPanel, userDAO);
            UsersListController listController = new UsersListController(listPanel, userDAO, mainFrame);
            DeleteUserController deleteController = new DeleteUserController(deletePanel, userDAO);
            UpdateUserController updateController = new UpdateUserController(updatePanel, userDAO);
            transactionalPanel = new TransactionalPanel();
            mainFrame.setTransactionalPanel(transactionalPanel);
            TransactionalController transactionalController = new TransactionalController(transactionalPanel, userDAO);
        });
        
    }
    
    public void setLogo(){
        logoLabel.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/resources/LogoBank.png")).getImage()
        .getScaledInstance(200, 100, 0)));
    }
    
    private void setCustomContentPanel(JPanel panel) {
        panel.setSize(250, 170);
        panel.setLocation(0, 0);

        jPanelContainer.removeAll();
        jPanelContainer.add(panel, BorderLayout.CENTER);
        jPanelContainer.revalidate();
        jPanelContainer.repaint();

        pack();
    }
    
    private void setTransactionalPanel(JPanel panel) {
        panel.setSize(420, 130);
        panel.setLocation(20, 20);
        
        jPanelTransactions.removeAll();
        jPanelTransactions.add(panel, BorderLayout.CENTER);
        jPanelTransactions.revalidate();
        jPanelTransactions.repaint();
    }

    public JButton getUsersListBtn() {
        return usersListBtn;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createUserBtn;
    private javax.swing.JButton deleteUserBtn;
    private javax.swing.JButton editUserBtn;
    private javax.swing.JPanel jPanelContainer;
    private javax.swing.JPanel jPanelTransactions;
    private javax.swing.JPanel jPanelUsers;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton usersListBtn;
    // End of variables declaration//GEN-END:variables
}
